//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPLabSheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSheet
    {
        public int OtherServerLabSheetID { get; set; }
        public string SamplingPlanName { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int RunNumber { get; set; }
        public int SubsectorTVItemID { get; set; }
        public int SamplingPlanType { get; set; }
        public int SampleType { get; set; }
        public int LabSheetType { get; set; }
        public int LabSheetStatus { get; set; }
        public string FileName { get; set; }
        public System.DateTime FileLastModifiedDate_Local { get; set; }
        public string FileContent { get; set; }
        public string AcceptedOrRejectedBy { get; set; }
        public Nullable<System.DateTime> AcceptedOrRejectedDate_Local { get; set; }
        public string RejectReason { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    }
}
